http {
    server{
        listen 0.0.0.0:3491;
        root ./test;
        
        location /
        {
            allow GET;
            autoindex on;
        }

        location /post_body
        {
            root ./test/post;
            allow POST GET;
            client_max_body_size 100;
        }

        location /directory/
        {
            alias ./test/YoupiBanane;
            allow GET;
            index youpi.bad_extension;
        }
    }
}